name: 'local-cache'
description: 'Cache artifacts to improve workflow execution time on self hosted machine'
inputs:
  path:
    description: 'Where to cache'
    required: true
  key:
    description: 'How to check cache hit'
    required: true
outputs:
  cache-hit:
    description: 'Cache hit or not'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()
